(source gnu)
(source melpa)

;; Packages for general improvements
(depends-on "bind-key")
(depends-on "expand-region")
(depends-on "hl-todo")
(depends-on "idle-highlight-mode")
(depends-on "smartparens")
(depends-on "rainbow-delimiters")
(depends-on "undo-tree")
(depends-on "which-key")
(depends-on "editorconfig")
(depends-on "smart-mode-line")
(depends-on "company")

(depends-on "helm")
(depends-on "helm-swoop")
(depends-on "helm-projectile")
(depends-on "helm-company")
(depends-on "helm-mode-manager") ;; TODO Add keybindings/hydra?

(depends-on "projectile")
(depends-on "org-projectile") ;; TODO Configure keybindings/hydra?
(depends-on "org-projectile-helm") ;; TODO Configure keybindings/hydra?

;; Git extended support TODO Revisit?
(depends-on "magit")

;; TODO Revisit
(depends-on "org-rainbow-tags")
(depends-on "org-roam")

;; TODO Revisit
(depends-on "hydra")

;; Check buffer on the fly
(depends-on "flycheck") ;; TODO Setup checks for all(?) prog-modes
(depends-on "flycheck-cask")
(depends-on "flycheck-color-mode-line")
(depends-on "helm-flycheck")
(depends-on "flyspell-correct-helm")

;; Python related
(depends-on "pyenv-mode")
(depends-on "python-mode")
(depends-on "company-anaconda")
(depends-on "flycheck-pycheckers")

;; Mostly programming related modes
(depends-on "json-mode")
(depends-on "json-reformat")
(depends-on "markdown-mode")
(depends-on "yaml-mode")
(depends-on "gradle-mode")
(depends-on "dockerfile-mode")
(depends-on "terraform-mode")
(depends-on "company-terraform")
(depends-on "swift-mode")
(depends-on "kotlin-mode")
(depends-on "cask-mode")

;; Themes
(depends-on "labburn-theme")
