(source gnu)
(source melpa)

(depends-on "cask")

;; Packages for general improvements
(depends-on "anzu")
(depends-on "bind-key")
(depends-on "expand-region")
(depends-on "fic-mode")
(depends-on "idle-highlight-mode")
(depends-on "helm")
(depends-on "helm-ls-git")
(depends-on "helm-swoop")
(depends-on "helm-projectile")
(depends-on "helm-company")
(depends-on "smartparens")
(depends-on "projectile")
(depends-on "org-projectile")
(depends-on "perspective")
(depends-on "persp-projectile")
(depends-on "rainbow-delimiters")
(depends-on "smart-mode-line")
(depends-on "smart-mode-line-powerline-theme")
(depends-on "undo-tree")
(depends-on "neotree")
(depends-on "which-key")
(depends-on "editorconfig")
(depends-on "ace-window")
(depends-on "ace-jump-mode")

;; Check buffer on the fly
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flymake-cursor")

;; Git extended support
(depends-on "magit")
(depends-on "magit-gerrit")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")

;; Scala
(depends-on "ensime")
(depends-on "scala-mode")

;; Modes for web related files like css, json etc
(depends-on "less-css-mode")
(depends-on "json-mode")
(depends-on "json-reformat")
(depends-on "markdown-mode")
(depends-on "web-mode")
(depends-on "tide")
(depends-on "yaml-mode")
(depends-on "ember-mode")

;; Go
(depends-on "go-mode")
(depends-on "company-go")
(depends-on "go-errcheck")
(depends-on "go-eldoc")

(depends-on "gradle-mode")
(depends-on "groovy-mode")
(depends-on "dockerfile-mode")

;; Themes
(depends-on "darcula-theme")
(depends-on "zerodark-theme")
(depends-on "zenburn-theme")
(depends-on "suscolors-theme")
(depends-on "color-theme-modern")
