(source gnu)
(source melpa)

(depends-on "cask")

;; Packages for general improvements
(depends-on "anzu")
(depends-on "auto-complete")
(depends-on "bind-key")
(depends-on "browse-kill-ring")
(depends-on "expand-region")
(depends-on "fic-mode")
(depends-on "idle-highlight-mode")
(depends-on "helm")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "flx-ido")
(depends-on "ido-vertical-mode")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "smart-mode-line")
(depends-on "undo-tree")

;; Check buffer on the fly
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flymake-cursor")

;; Git extended support
(depends-on "magit")
(depends-on "magit-gerrit")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")

;; Scala
(depends-on "ensime")
(depends-on "scala-mode2")

;; Modes for web related files like css, json etc
(depends-on "less-css-mode")
(depends-on "json-mode")
(depends-on "json-reformat")
(depends-on "markdown-mode")
(depends-on "web-mode")

;; Go
(depends-on "go-mode")
(depends-on "go-autocomplete")
(depends-on "go-errcheck")
(depends-on "go-eldoc")

;; Rust
(depends-on "rust-mode")
(depends-on "racer")
(depends-on "ac-racer")
;; (depends-on "company")

;; Themes
(depends-on "darcula-theme")
(depends-on "zerodark-theme")
(depends-on "zenburn-theme")
